<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5fc93d4548191',
	'title' => 'Items Banner',
	'fields' => array(
		array(
			'key' => 'field_5fc93d4d1c9c1',
			'label' => '',
			'name' => 'title-items-banner',
			'type' => 'text',
			'instructions' => 'Título',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fc93d611c9c2',
			'label' => '',
			'name' => 'subtitle-items-banner',
			'type' => 'text',
			'instructions' => 'Subtítulo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fc93d861c9c4',
			'label' => '',
			'name' => 'image-items-banner',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5fc93da81c9c5',
			'label' => '',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Pre Banner',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array(
			'key' => 'field_5fc93dd71c9c6',
			'label' => '',
			'name' => 'title-items-prev-banner',
			'type' => 'text',
			'instructions' => 'Título Pre Banner',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fc93e0b1c9c7',
			'label' => '',
			'name' => 'image-items-prev-banner',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'itemsbanner',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5fd0f06395b43',
	'title' => 'Items Team',
	'fields' => array(
		array(
			'key' => 'field_5fd0f06e6dae8',
			'label' => '',
			'name' => 'name_team',
			'type' => 'text',
			'instructions' => 'Nombre',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fd0f0976dae9',
			'label' => '',
			'name' => 'cargo_team',
			'type' => 'text',
			'instructions' => 'Cargo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fd0f0a76daea',
			'label' => '',
			'name' => 'image_team',
			'type' => 'image',
			'instructions' => 'Foto',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'itemsteam',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5fcfb9ee96b9d',
	'title' => 'Plantillas Páginas',
	'fields' => array(
		array(
			'key' => 'field_5fcfbaef144e6',
			'label' => '',
			'name' => 'template_scelestia',
			'type' => 'select',
			'instructions' => 'Plantillas',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Página General' => 'Página General',
				'Nosotros' => 'Nosotros',
				'Lo nuevo' => 'Lo nuevo',
				'Lo más vendido' => 'Lo más vendido',
				'Políticas' => 'Políticas',
				'Contacto' => 'Contacto',
				'Ninguno' => 'Ninguno',
			),
			'default_value' => 'Ninguno',
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5fcfd6a1da771',
			'label' => 'Políticas',
			'name' => 'title-banner-politicas',
			'type' => 'text',
			'instructions' => 'Título',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Políticas',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fcfd6b9da772',
			'label' => '',
			'name' => 'subtitle-banner-politicas',
			'type' => 'text',
			'instructions' => 'Subtítulo',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Políticas',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fcfbb62144e7',
			'label' => 'Página General',
			'name' => 'title-banner-general-page',
			'type' => 'text',
			'instructions' => 'Título',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Página General',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fcfbba1144e8',
			'label' => '',
			'name' => 'subtitle-banner-general-page',
			'type' => 'text',
			'instructions' => 'Subtítulo',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Página General',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fcfbce2b0101',
			'label' => 'Lo nuevo',
			'name' => 'title-banner-nuevo',
			'type' => 'text',
			'instructions' => 'Título',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Lo nuevo',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fcfbd31b0102',
			'label' => '',
			'name' => 'subtitle-banner-nuevo',
			'type' => 'text',
			'instructions' => 'Subtítulo',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Lo nuevo',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fcfbd54b0103',
			'label' => '',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Lo nuevo',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Sección Descubre',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array(
			'key' => 'field_5fcfbdc9b0104',
			'label' => '',
			'name' => 'buttom-central-nuevo',
			'type' => 'text',
			'instructions' => 'Botón Central',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Lo nuevo',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fcfbdeab0105',
			'label' => '',
			'name' => 'urlbuttom-central-nuevo',
			'type' => 'text',
			'instructions' => 'Url Botón Central',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Lo nuevo',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fcfbe49b0106',
			'label' => '',
			'name' => 'image-descubre-nuevo',
			'type' => 'image',
			'instructions' => 'Imagen Fondo',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Lo nuevo',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5fcfbeabb0107',
			'label' => '',
			'name' => 'title-descubre-nuevo',
			'type' => 'text',
			'instructions' => 'Título',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Lo nuevo',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fcfbee6b0108',
			'label' => '',
			'name' => 'subtitle-descubre-nuevo',
			'type' => 'text',
			'instructions' => 'Subtítulo',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Lo nuevo',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fcfbf0cb0109',
			'label' => '',
			'name' => 'description-descubre-nuevo',
			'type' => 'textarea',
			'instructions' => 'Descripción',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Lo nuevo',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5fcfbf39b010a',
			'label' => '',
			'name' => 'buttom-descubre-nuevo',
			'type' => 'text',
			'instructions' => 'Botón Descubre',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Lo nuevo',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fcfbf75b010b',
			'label' => '',
			'name' => 'urlbuttom-descubre-nuevo',
			'type' => 'text',
			'instructions' => 'Url Botón',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Lo nuevo',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fcfcea9eb6f5',
			'label' => 'Lo más vendido',
			'name' => 'title-banner-vendido',
			'type' => 'text',
			'instructions' => 'Título',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Lo más vendido',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fcfceb1eb6f6',
			'label' => '',
			'name' => 'subtitle-banner-vendido',
			'type' => 'text',
			'instructions' => 'Subtítulo',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Lo más vendido',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fcfceb5eb6f7',
			'label' => '',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Lo más vendido',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Sección Descubre',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array(
			'key' => 'field_5fcfcebeeb6f8',
			'label' => '',
			'name' => 'buttom-central-vendido',
			'type' => 'text',
			'instructions' => 'Botón Central',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Lo más vendido',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fcfcec4eb6f9',
			'label' => '',
			'name' => 'urlbuttom-central-vendido',
			'type' => 'text',
			'instructions' => 'Url Botón Central',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Lo más vendido',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fcfcecaeb6fa',
			'label' => '',
			'name' => 'image-descubre-vendido',
			'type' => 'image',
			'instructions' => 'Imagen Fondo',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Lo más vendido',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5fcfceceeb6fb',
			'label' => '',
			'name' => 'title-descubre-vendido',
			'type' => 'text',
			'instructions' => 'Título',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Lo más vendido',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fcfced7eb6fc',
			'label' => '',
			'name' => 'subtitle-descubre-vendido',
			'type' => 'text',
			'instructions' => 'Subtítulo',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Lo más vendido',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fcfcedbeb6fd',
			'label' => '',
			'name' => 'description-descubre-vendido',
			'type' => 'textarea',
			'instructions' => 'Descripción',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Lo más vendido',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5fcfcee1eb6fe',
			'label' => '',
			'name' => 'buttom-descubre-vendido',
			'type' => 'text',
			'instructions' => 'Botón Descubre',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Lo más vendido',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fcfcee4eb6ff',
			'label' => '',
			'name' => 'urlbuttom-descubre-vendido',
			'type' => 'text',
			'instructions' => 'Url Botón',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Lo más vendido',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fcfd807b1a57',
			'label' => 'Contacto',
			'name' => 'title-banner-contacto',
			'type' => 'text',
			'instructions' => 'Título',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Contacto',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fcfd83fd5743',
			'label' => '',
			'name' => 'image-banner-contacto',
			'type' => 'image',
			'instructions' => 'Imagen Banner',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Contacto',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5fcfd874d5744',
			'label' => '',
			'name' => 'map-contacto',
			'type' => 'textarea',
			'instructions' => 'Mapa Ubicación',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Contacto',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5fd0ea0b73aca',
			'label' => 'Nosotros',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Nosotros',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Item 1',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array(
			'key' => 'field_5fd0e99973ac9',
			'label' => '',
			'name' => 'title-item1-nosotros',
			'type' => 'text',
			'instructions' => 'Título',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Nosotros',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fd0eb1f73acd',
			'label' => '',
			'name' => 'subtitle-item1-nosotros',
			'type' => 'text',
			'instructions' => 'Subtítulo',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Nosotros',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fd0eb4473ace',
			'label' => '',
			'name' => 'description-item1-nosotros',
			'type' => 'textarea',
			'instructions' => 'Descripción',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Nosotros',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5fd0eaa273acc',
			'label' => '',
			'name' => 'image1-item1-nosotros',
			'type' => 'image',
			'instructions' => 'Imagen 1',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Nosotros',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5fd0ea7a73acb',
			'label' => '',
			'name' => 'image2-item1-nosotros',
			'type' => 'image',
			'instructions' => 'Imagen 2',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Nosotros',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5fd0eb7d1f53c',
			'label' => '',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Nosotros',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Item 2',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array(
			'key' => 'field_5fd0eb921f53d',
			'label' => '',
			'name' => 'title-item2-nosotros',
			'type' => 'text',
			'instructions' => 'Título',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Nosotros',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fd0eb981f53e',
			'label' => '',
			'name' => 'subtitle-item2-nosotros',
			'type' => 'text',
			'instructions' => 'Subtítulo',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Nosotros',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fd0eba11f53f',
			'label' => '',
			'name' => 'description-item2-nosotros',
			'type' => 'textarea',
			'instructions' => 'Descripción',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Nosotros',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5fd0ebac1f540',
			'label' => '',
			'name' => 'image1-item2-nosotros',
			'type' => 'image',
			'instructions' => 'Imagen 1',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Nosotros',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5fd0ebb31f541',
			'label' => '',
			'name' => 'image2-item2-nosotros',
			'type' => 'image',
			'instructions' => 'Imagen 2',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Nosotros',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5fd0ec3d1f542',
			'label' => '',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Nosotros',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Item 3',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array(
			'key' => 'field_5fd0ec601f545',
			'label' => '',
			'name' => 'title-item3-nosotros',
			'type' => 'text',
			'instructions' => 'Título',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Nosotros',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fd0ec7b1f546',
			'label' => '',
			'name' => 'subtitle-item3-nosotros',
			'type' => 'text',
			'instructions' => 'Subtítulo',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Nosotros',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fd0ec841f548',
			'label' => '',
			'name' => 'description-item3-nosotros',
			'type' => 'textarea',
			'instructions' => 'Descripción',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Nosotros',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5fd0ec9d1f54a',
			'label' => '',
			'name' => 'image1-item3-nosotros',
			'type' => 'image',
			'instructions' => 'Imagen 1',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Nosotros',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5fd0ecbb1f54c',
			'label' => '',
			'name' => 'image2-item3-nosotros',
			'type' => 'image',
			'instructions' => 'Imagen 1',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Nosotros',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5fd0ed911f54e',
			'label' => '',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Nosotros',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Sección Razones',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array(
			'key' => 'field_5fd0ee1b0d348',
			'label' => '',
			'name' => 'title-razones-nosotros',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Nosotros',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fd0ee790d349',
			'label' => '',
			'name' => 'title-razones1-nosotros',
			'type' => 'text',
			'instructions' => 'Descripción Razón 1',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Nosotros',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fd0ee9d0d34a',
			'label' => '',
			'name' => 'image-razones1-nosotros',
			'type' => 'image',
			'instructions' => 'Icono Razón 1',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Nosotros',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5fd0eef80d34b',
			'label' => '',
			'name' => 'title-razones2-nosotros',
			'type' => 'text',
			'instructions' => 'Descripción Razón 2',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Nosotros',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fd0ef1e0d34c',
			'label' => '',
			'name' => 'image-razones2-nosotros',
			'type' => 'image',
			'instructions' => 'Icono Razón 2',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Nosotros',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5fd0ef320d34d',
			'label' => '',
			'name' => 'title-razones3-nosotros',
			'type' => 'text',
			'instructions' => 'Descripción Razón 3',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Nosotros',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fd0ef460d34e',
			'label' => '',
			'name' => 'image-razones3-nosotros',
			'type' => 'image',
			'instructions' => 'Icono Razón 3',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Nosotros',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5fd0f4f32f8ad',
			'label' => '',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Nosotros',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Sección Team',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array(
			'key' => 'field_5fd0f5152f8ae',
			'label' => '',
			'name' => 'title-team-nosotros',
			'type' => 'text',
			'instructions' => 'Título',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Nosotros',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fd0f5342f8af',
			'label' => '',
			'name' => 'subtitle-team-nosotros',
			'type' => 'text',
			'instructions' => 'Subtítulo',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Nosotros',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fd0f54f2f8b0',
			'label' => '',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fcfbaef144e6',
						'operator' => '==',
						'value' => 'Nosotros',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '<a href="edit.php?post_type=itemsteam">Agregar Team Aquí >></a>',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

endif;
?>